// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwT9oFlmDD9F-b0OQ0S8G3Deo2kwgZaw',
    appId: '1:1055700920383:web:2ef237792d5d5d4bd9308a',
    messagingSenderId: '1055700920383',
    projectId: 'oway-cc924',
    authDomain: 'oway-cc924.firebaseapp.com',
    storageBucket: 'oway-cc924.appspot.com',
    measurementId: 'G-T66WPNZPTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKQDpM26-BlTStCTFCZi8QHE9kJenIxA',
    appId: '1:1055700920383:android:8af5844376d06ee0d9308a',
    messagingSenderId: '1055700920383',
    projectId: 'oway-cc924',
    storageBucket: 'oway-cc924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAExVxbaNfRiabS0thvpYB3vDKX6fuSUaE',
    appId: '1:1055700920383:ios:c950383defcdaffbd9308a',
    messagingSenderId: '1055700920383',
    projectId: 'oway-cc924',
    storageBucket: 'oway-cc924.appspot.com',
    iosBundleId: 'com.example.oway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAExVxbaNfRiabS0thvpYB3vDKX6fuSUaE',
    appId: '1:1055700920383:ios:c950383defcdaffbd9308a',
    messagingSenderId: '1055700920383',
    projectId: 'oway-cc924',
    storageBucket: 'oway-cc924.appspot.com',
    iosBundleId: 'com.example.oway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBwT9oFlmDD9F-b0OQ0S8G3Deo2kwgZaw',
    appId: '1:1055700920383:web:558c38953e30d760d9308a',
    messagingSenderId: '1055700920383',
    projectId: 'oway-cc924',
    authDomain: 'oway-cc924.firebaseapp.com',
    storageBucket: 'oway-cc924.appspot.com',
    measurementId: 'G-Y6V1R9YNZY',
  );
}
